### ISSUE TITLE
Just adding it to a UIImageView

### ISSUE THREAD

**Issue by jsetting32** [danielgindi/DGCurvedLabel#1]
Hi Daniel,

I am just attempting to add the curved label to a UIImageView. It doesn't seem to be rendering the text though. I create the same UILabel and add it to the view and it works (without the curved part). But then when I add the curved label (DGCurvedLabel) it doesn't work... Heres the code

``` Objective-C
- (void)layoutSubviews {
    [super layoutSubviews];

    self.profileImageView.frame = CGRectMake( 0.0f, 0.0f, self.frame.size.width, self.frame.size.height);
    self.profileButton.frame = CGRectMake( 0.0f, 0.0f, self.frame.size.width, self.frame.size.height);
    self.curvedLabel.frame = CGRectMake( 10.0f, 10.0f, self.frame.size.width - 20, self.frame.size.height - 20);
}
- (void)setUserForImage:(PFUser *)user
{
    [self.curvedLabel setText:[user objectForKey:kPHUserFirstNameKey]];
}
- (DGCurvedLabel *)curvedLabel
{
    if (!_curvedLabel) {
        _curvedLabel = [[DGCurvedLabel alloc] init];
        [_curvedLabel setFont:[UIFont fontWithName:kPHFont size:16.0f]];
        [_curvedLabel setBackgroundColor:[UIColor clearColor]];
        [_curvedLabel setTextInside:YES];
    }
    return _curvedLabel;
}

```

Sorry for the additional code but I just copy and pasted. So I have a lazy loading DGCurvedLabel and I add it to the subview in the initializer method. The current class that this is all embedded in is a UITableViewCell. If I change DGCurvedLabel to a UILabel, it works as said before. But then changing it back to a DGCurvedLabel, nothing is being rendered... But maybe it is but it may be outside the bounds of the UIImageView? But I explicitly set the frame of the Label in layoutSubviews. Any ideas?

**Comment by danielgindi** [comment]
Have you set the 'radius' around which you want to curve the label?

**Comment by jsetting32** [comment]
Hi Daniel,

Yes I have set it to 5.0f

**Comment by danielgindi** [comment]
Well I'd have to take a look at it...
In the meanwhile can play with it in Interface Builder just to see how it behaves with the same data you are passing.

**Comment by jsetting32** [comment]
Aight no prob. Thanks for your quick response

**Comment by danielgindi** [comment]
If you want to give me the exact inputs, like frame, text, radius etc - that could help in reproducing the problem

**Comment by danielgindi** [comment]
Any news on that?
